version: "3"
services:
   db:
    container_name: db_mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=nsocial_dev
    volumes:
      - $PWD/data:/data/db
    networks:
      - net
    ports:
      - '27017:27017'

networks:
  net:
